### ISSUE TITLE
Incompatibilities with http-lwt-client > 0.1.0

### ISSUE THREAD

**Issue by tmcgilchrist** [kit-ty-kate/ocaml-docker-hub#2]
```
File "vendor/ocaml-docker-hub/src/docker_hub.ml", line 21, characters 4-31:
21 |     Http_lwt_client.one_request
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Http_lwt_client.one_request
```
This API was changed in 0.1.0, would it be possible to release a new version that is compatible with latest [http-lwt-client](https://github.com/roburio/http-lwt-client).

**Comment by kit-ty-kate** [comment]
Done at https://github.com/ocaml/opam-repository/pull/23474
